### ISSUE TITLE
Upload savefile using path

### ISSUE THREAD

**Issue by koutoftimer** [dfederm/ClickerHeroesTracker#224] opened 2017-12-03 14:09 UTC
As you can see here: "https://graceoflives.github.io/fluffy-garbanzo/", savefile data can be obtained by specifying only path info (you don't have to copy and past savefile data by hands) and it is really helpful.

**Comment by dfederm** [comment] 2017-12-03 17:41
Dupe of #160

**Closed by dfederm** 2017-12-03 17:41 UTC
